const React = require('react');
// We're going to use this open source forms library to create our
// madlib form
const t = require('tcomb-form');
const { Form } = t.form;
const $ = require('jquery');

const MadlibForm = React.createClass({
  // this is the function that renders the form. most of the HTML
  // is generated by the forms library, so you're pretty much stuck to
  // how they format it.
  getDefaultProps: function() {
    return {
      requireError: 'oops, you missed this one',
      endingWithLyError: 'this one has to end with "ly"'
    };
  },


  render: function() {
    return (
      <div className='madlib-form'>
        <h3>Flocabulary Madlib</h3>
        <form onSubmit={this.onSubmit}>
          <Form
            ref="form"
            onChange={this.onChange}
            value={this.state.value}
            type={this.state.type}
            options={this.state.options}
          />
          {
            Object.keys(this.state.value).filter(key => this.state.value[key]).length === Object.keys(this.state.inputs).length
            ? (
                <button
                  className="submit-button"
                  type="submit"
                >
                  Make your mad lib!
                </button>
              )
            : null
          }
        </form>
      </div>
    );
  },
  // you probably shouldn't have to touch any of the other functions
  // on this class
  getInitialState: function() {
    let inputs = {};
    let result;

    t.String.getValidationErrorMessage = (value, path) => {
      if (!value) {
        return this.props.requireError;
      }
      if (path[0] === 'wordEndingWithLy' && !value.endsWith('ly')) {
        return this.props.endingWithLyError;
      }
    }

    let blankRegexp = /%&(.*?)&%/gi;
    while (result = blankRegexp.exec(this.props.text)) {
      let fieldType;
      if (result[1] === 'wordEndingWithLy') {
        fieldType = t.refinement(t.String, s => s.endsWith('ly'));
      } else if (result[1] === 'number') {
        fieldType = t.Number;
      } else {
        fieldType = t.String;
      }

      inputs[result[1]] = fieldType;
    }

    return {
      type: t.struct(inputs),
      options: {
        fields: {
          number: {
            type: 'number'
          }
        }
      },
      value: {},
      submitted: false,
      inputs: inputs,
    };
  },

  componentDidMount: function() {
    // $('.form-group form-group-depth-1 form-group').focus(e => {
    //   $('.form-group form-group-depth-1 form-group'+ e).removeClass('.form-group form-group-depth-1 form-group');
    //   $(e.target).parent().addClass('.form-group form-group-depth-1 form-group');
    // })

    // $( ".madlib-form input" ).on('blur', function() {
    //   if($(this).val() != '') {
    //     $(this).next('.madlib-form input').fadeIn('slow');
    // }});

    // $(document).keypress('keypress', function(e){
    //   if(e.which==13){
    //     $('.form-group form-group-depth-1 form-group').show()
    //   }
    // })
  },

  onSubmit: function(event) {
    event.preventDefault();
    if (this.formsAreValid()) {
      this.props.onSubmit(this.getFormValues());
    }
  },
  onChange: function(value, path) {
    this.setState(
      { value: value },
      () => {
        this.refs.form.getComponent(path).validate();
      }
    );
  },
  formsAreValid: function() {
    return !this.refs.form.validate().errors.length;
  },
  getFormValues: function() {
    return this.refs.form.getValue();
  }
});

module.exports = MadlibForm;
